name:                lusynth
version:             0.1.0.0
github:              "lslunis/lusynth"
author:              "Luke Stebbing"
maintainer:          "ls@lunis.net"
copyright:           "2020 Luke Stebbing"

extra-source-files:
- README.md

description:         <https://github.com/lslunis/lusynth#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lusynth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lusynth

tests:
  lusynth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lusynth
